<style>
    body{
	margin:0;
	color:#aaa;
	background-image: linear-gradient(to bottom,rgba(22,22,22,.1) 0,rgba(22,22,22,.5) -19%,#000 100%),url(../img/fundo-home.jpg) !important;
	font:600 16px/18px 'Open Sans',sans-serif;
    }
</style>

<link href="/css/login.css" rel="stylesheet">

<div class="main" style="margin-bottom: 50px;">
    <div class="login-wrap">
        <div class="login-html">
            <input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">Login</label>
            <input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab">Registrar</label>
            <div class="login-form">
                <div class="sign-in-htm">
                    <div class="group">
                        <label for="user" class="label">Usuário</label>
                        <input id="luser" type="text" class="form-control">
                    </div>
                    <div class="group">
                        <label for="pass" class="label">Senha</label>
                        <input id="lpass" type="password" class="form-control" data-type="password">
                    </div>
                    <div class="foot-lnk">
                        <a href="">Esqueceu a senha?</a>
                    </div>
                    <div class="group">
                        <input type="submit" class="button" value="Entrar">
                    </div>
                    <div class="hr"></div>
                </div>
                <div class="sign-up-htm">
                    <div class="group">
                        <label for="user" class="label">Usuario</label>
                        <input id="ruser" type="text" class="form-control">
                    </div>
                    <div class="group">
                        <label for="pass" class="label">Senha</label>
                        <input id="rpass" type="password" class="form-control" data-type="password">
                    </div>
                    <div class="group">
                        <label for="pass" class="label">Repita a senha</label>
                        <input id="rpass" type="password" class="form-control" data-type="password">
                    </div>
                    <div class="group">
                        <label for="pass" class="label">E-mail</label>
                        <input id="rpass" type="text" class="form-control">
                    </div>
                    <div class="group">
                        <input type="submit" class="button" value="Registrar-se">
                    </div>
                    <div class="hr"></div>
                </div>
            </div>
        </div>
    </div>
</div>