
<style>
    body{
        background-color: #fff !important;
    }
    .fundo{
        position: absolute !important;
        left: 0px;
        right: 0px;
        top:50px;
        max-height: 300px !important;
        background:linear-gradient(to bottom,rgba(22,22,22,.1) 0,rgba(22,22,22,.5) -19%,#000 100%),url(../img/fundo-home.jpg);
        min-height:35rem;
        background-position:center;
        background-repeat:no-repeat;
        background-attachment:scroll;
        background-size:cover
    }
    .tittle{
        background: none !important;
        position: relative !important;
        margin-top: 270px;
    }
    .corText{
        color: rgba(0, 0, 0, 0.5) !important;
    }
    .class{
        filter: saturate(0.25);
        -webkit-filter: saturate(0.25);
    }
    .padding2{
        padding-left: 85px;
        padding-right: 85px;
    }
    .padding3{
        padding: 3rem !important;
    }
</style>
<head>
    <link href="/css/css" rel="stylesheet">
    <link href="/css/css(1)" rel="stylesheet">
    <link href="/css/grayscale.min.css" rel="stylesheet">
    <link href="/css/bt-steps.css" rel="stylesheet">
</head>
<body id="page-top">
    <header class="fundo">
    </header>
    <div class='titulo tittle'>
        <div class="container d-flex h-60 align-items-center">
            <div class="mx-auto text-center">
                <h1 class="mx-auto my-0 text-uppercase">Class</h1>
                <h2 class="text-white-50 mx-auto mt-2 mb-5">Uma escolha gratuita e educacional para quem procura um gerenciamento de projetos e tarefas.</h2>
            </div>
        </div>
    </div>
    
    <section id="projects" class="projects-section bg-light">
        <div class="container">
            <!-- Featured Project Row -->
            <div class="row align-items-center no-gutters mb-4 mb-lg-5">
                <div class="col-xl-7 col-lg-7">
                    <img class="img-fluid mb-3 mb-lg-0 class" src="/img/class.jpeg" alt="">
                </div>
                <div class="col-xl-5 col-lg-5">
                    <div class="featured-text text-center text-lg-left">
                        <h4 class="corText">UTILIDADES</h4>
                        <p class="text-black-50 mb-0">O CLASS é um Sistema Educacional que oferece aos seus usuarios aplicações que os auxiliam no gerenciamento e na participação em salas de aulas, em novos projetos e novas equipes.</p>
                    </div>
                </div>
            </div>
            
            <div style="margin-top: 20px">
                <div class="col-md-12 padding2">
                    <div class="steps-form-2">
                        <div class="steps-row-2 setup-panel-2 d-flex justify-content-between">
                            <div class="steps-step-2">
                                <a class="btn btn-amber btn-circle-2 waves-effect ml-0"><i class="fa fa-users" aria-hidden="true"></i></a>
                            </div>
                            <div class="steps-step-2">
                                <a class="btn btn-blue-grey btn-circle-2 waves-effect"><i class="fa fa-clipboard" aria-hidden="true"></i></a>
                            </div>
                            <div class="steps-step-2">
                                <a class="btn btn-blue-grey btn-circle-2 waves-effect"><i class="fa fa-check-square-o" aria-hidden="true"></i></a>
                            </div>
                            <div class="steps-step-2">
                                <a class="btn btn-blue-grey btn-circle-2 waves-effect mr-0"><i class="fa fa-users" aria-hidden="true"></i></a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row text-center" style="margin-top: 10px">
                    <div class="col-md-3 bg-black-transp border-inner-7" style="background-clip: content-box;">
                        Crie uma Nova Sala
                    </div>
                    <div class="col-md-3 bg-black-transp border-inner-7" style="background-clip: content-box;">
                        Crie Novos Projetos
                    </div>
                    <div class="col-md-3 bg-black-transp border-inner-7" style="background-clip: content-box;">
                        Crie Novas Atividades
                    </div>
                    <div class="col-md-3 bg-black-transp border-inner-7" style="background-clip: content-box;">
                        Gerencie Equipes
                    </div>
                </div>
            </div>
        </div>
    </section>
    <footer class="bg-black small text-center text-white-50">
        <section>
        <div class="row justify-content-center no-gutters mb-5 mb-lg-0">
            <div class="col-lg-12">
                <div class="bg-black text-center h-100 project">
                    <div class="d-flex h-100">
                        <div class="col-md-4">
                            <div class="padding3 project-text w-100 my-auto text-center text-lg-left">
                                <h4 class="text-white">TIMELINE <i class="fa fa-user" aria-hidden="true"></i></h4>
                                <p class="mb-0 text-white-50">Compartilhe o que quiser em sua TIMELINE.</p>
                                <hr class="d-none d-lg-block mb-0 ml-0">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="padding3 project-text w-100 my-auto text-center text-lg-left">
                                <h4 class="text-white">RELATÓRIOS <i class="fa fa-line-chart" aria-hidden="true"></i></h4>
                                <p class="mb-0 text-white-50">Relatorios de desempenho pessoal e/ou de sua equipe em um projeto</p>
                                <hr class="d-none d-lg-block mb-0 ml-0">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="padding3 project-text w-100 my-auto text-center text-lg-left">
                                <h4 class="text-white">CHAT <i class="fa fa-comments-o" aria-hidden="true"></i></h4>
                                <p class="mb-0 text-white-50">Mande mensagens para seus amigos.</p>
                                <hr class="d-none d-lg-block mb-0 ml-0">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </section>
    </footer>
</body>
</html>