<script type="text/javascript" src="/js/dragula.js"></script>
<script type="text/javascript" src="/js/dragula.min.js"></script>
<link rel="stylesheet" href="/css/dragula.css"/> 
<link rel="stylesheet" href="/css/dragula.min.css"/> 
<link rel="stylesheet" href="/css/drag.css"/> 

<style>

</style>

<div class="main">
    <div class="col-md-12">
        <div class="drag-container">
            <ul class="drag-list">
                <li class="drag-column drag-column-on-hold">
                    <span class="drag-column-header">
                        <h2 class="txttile"><i class="fa fa-file-text"></i>&nbsp;TO DO</h2>
                        <svg class="drag-header-more" data-target="options1" fill="#FFFFFF" height="24" viewBox="0 0 24 24" width="24"><path d="M0 0h24v24H0z" fill="none"/><path d="M12 8c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm0 2c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm0 6c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2z"/</svg>
                    </span>

                    <div class="drag-options" id="options1"></div>

                    <ul class="drag-inner-list" id="1">
                        <div class="drag-item">Criticar</div>
                        <li class="drag-item">Zoar</li>
                    </ul>
                </li>
                <li class="drag-column drag-column-in-progress">
                    <span class="drag-column-header">
                        <h2 class="txttile"><i class="fa fa-spinner"></i>&nbsp;In Progress</h2>
                    </span>
                    <div class="drag-options" id="options2"></div>
                    <ul class="drag-inner-list" id="2">
                    </ul>
                </li>
                <li class="drag-column drag-column-needs-review">
                    <span class="drag-column-header">
                        <h2 class="txttile"><i class="fa fa-exclamation-circle">&nbsp;To Verify</i></h2>
                        <svg data-target="options3" class="drag-header-more" fill="#FFFFFF" height="24" viewBox="0 0 24 24" width="24"><path d="M0 0h24v24H0z" fill="none"/><path d="M12 8c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm0 2c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm0 6c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2z"/</svg>
                    </span>
                    <div class="drag-options" id="options3"></div>
                    <ul class="drag-inner-list" id="3">
                    </ul>
                </li>
                <li class="drag-column drag-column-approved">
                    <span class="drag-column-header">
                       
                        <h2 class="txttile"><i class="fa fa-check-circle"></i>&nbsp;Done</h2>
                        <svg data-target="options4" class="drag-header-more" fill="#FFFFFF" height="24" viewBox="0 0 24 24" width="24"><path d="M0 0h24v24H0z" fill="none"/><path d="M12 8c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm0 2c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm0 6c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2z"/</svg>
                    </span>
                    <div class="drag-options" id="options4"></div>
                    <ul class="drag-inner-list" id="4">
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>

<script>
    
    dragula([
        $('#1')[0],
        $('#2')[0],
        $('#3')[0],
        $('#4')[0],
        $('#5')[0]
    ])

    .on('drag', function(el) {
        // add 'is-moving' class to element being dragged
        el.classList.add('is-moving');
    })
    .on('dragend', function(el) {
        // remove 'is-moving' class from element after dragging has stopped
        el.classList.remove('is-moving');

        // add the 'is-moved' class for 600ms then remove it
        window.setTimeout(function() {
                el.classList.add('is-moved');
                window.setTimeout(function() {
                        el.classList.remove('is-moved');
                }, 600);
        }, 100);
    });
    
    
</script>